# Dependencies
markdown: kramdown
kramdown:
  input: GFM
highlighter: pygments
plugins:
  - github-pages
  - jekyll-paginate

# Permalinks
permalink: pretty

# Pagination
paginate: 5

# Setup

title: Martin Cepeda
tagline: Personal site
description: 'Portfolio & random thoughts'
baseurl: ''
author:
  name: 'Martin Cepeda'
  url: https://github.com/cepedus
github:
  repo: https://github.com/cepedus/cepedus.github.io

exclude: [latex]

# Custom vars
profiles:
  github: https://github.com/cepedus
  linkedin: https://www.linkedin.com/in/cepedus/ 

# Archives
collections:
  archives:
    output: true
    permalink: /archives/:path/